# Generated by Django 6.0.6 on 2026-06-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicemodel",
            name="locked_coin_price",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="invoicemodel",
            name="locked_gold_price",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="invoicemodel",
            name="weight",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="expire_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Expire At"),
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="locked_price_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Locked Price At"
            ),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="order_type",
            field=models.CharField(
                choices=[
                    ("buy_product", "Buy Product"),
                    ("sell_product", "Sell Product"),
                    ("buy_coin", "Buy Coin"),
                    ("sell_coin", "Sell Coin"),
                    ("buy_melted_gold", "Buy Melted Gold"),
                    ("sell_melted_gold", "Sell Melted Gold"),
                ],
                max_length=20,
            ),
        ),
    ]
