# Generated by Django 6.0.6 on 2026-09-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_invoicemodel_locked_coin_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoicemodel",
            name="locked_coin_price",
        ),
        migrations.RemoveField(
            model_name="invoicemodel",
            name="locked_gold_price",
        ),
        migrations.AddField(
            model_name="invoicemodel",
            name="title",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Title"
            ),
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="invoice_generated",
            field=models.BooleanField(default=False, verbose_name="Invoice Generated"),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="order_type",
            field=models.CharField(
                choices=[
                    ("buy_product", "Buy Product"),
                    ("buy_coin", "Buy Coin"),
                    ("sell_coin", "Sell Coin"),
                    ("buy_melted_gold", "Buy Melted Gold"),
                    ("sell_melted_gold", "Sell Melted Gold"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("wallet", "Wallet"),
                    ("gateway", "Gateway"),
                    ("cash", "Cash Payment"),
                ],
                max_length=20,
                null=True,
                verbose_name="Payment Method",
            ),
        ),
    ]
