# Generated by Django 6.0.6 on 2026-06-06 09:34

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoryModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update Time"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted Time"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="product/icons",
                        verbose_name="Icon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="GoldPriceModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update Time"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted Time"
                    ),
                ),
                (
                    "gold_melted",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=18,
                        verbose_name="Melted Gold Price",
                    ),
                ),
                (
                    "gold_ounce",
                    models.DecimalField(
                        decimal_places=0, max_digits=18, verbose_name="Gold Ounce Price"
                    ),
                ),
                (
                    "gold_mozanneh",
                    models.DecimalField(
                        decimal_places=0, max_digits=18, verbose_name="Muzanneh Price"
                    ),
                ),
                (
                    "quarter_coin",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=18,
                        verbose_name="Quarter Coin Price",
                    ),
                ),
                (
                    "half_coin",
                    models.DecimalField(
                        decimal_places=0, max_digits=18, verbose_name="Half Coin Price"
                    ),
                ),
                (
                    "full_coin",
                    models.DecimalField(
                        decimal_places=0, max_digits=18, verbose_name="Full Coin Price"
                    ),
                ),
                (
                    "emami_coin",
                    models.DecimalField(
                        decimal_places=0, max_digits=18, verbose_name="Emami Coin Price"
                    ),
                ),
            ],
            options={
                "verbose_name": "Gold Price",
                "verbose_name_plural": "Gold Prices",
            },
        ),
        migrations.CreateModel(
            name="CoinModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update Time"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted Time"
                    ),
                ),
                (
                    "coin_type",
                    models.CharField(
                        choices=[
                            ("quarter", "Quarter"),
                            ("half", "Half"),
                            ("full", "Full"),
                            ("emai", "Emai"),
                        ],
                        max_length=20,
                        verbose_name="Coin Type",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="product/images",
                        verbose_name="Image",
                    ),
                ),
                (
                    "buy_price",
                    models.DecimalField(
                        decimal_places=0, max_digits=18, verbose_name="Buy Price"
                    ),
                ),
                (
                    "sell_price",
                    models.DecimalField(
                        decimal_places=0, max_digits=18, verbose_name="Sell Price"
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=10,
                        verbose_name="Weight (grams)",
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0, verbose_name="Stock")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
            ],
            options={
                "verbose_name": "Coin",
                "verbose_name_plural": "Coins",
                "unique_together": {("coin_type",)},
            },
        ),
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update Time"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted Time"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="product/images",
                        verbose_name="Image",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="Weight (grams)"
                    ),
                ),
                (
                    "wage_percent",
                    models.DecimalField(
                        decimal_places=4, max_digits=5, verbose_name="Wage (%)"
                    ),
                ),
                (
                    "tax_percent",
                    models.DecimalField(
                        decimal_places=4, max_digits=5, verbose_name="Tax (%)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("out_of_stock", "Out Of Stock"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="product.categorymodel",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
    ]
