# Generated by Django 6.0.6 on 2026-06-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodel",
            name="tax_percent",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Tax (%)"
            ),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="wage_percent",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Wage (%)"
            ),
        ),
    ]
