# Generated by Django 6.0.6 on 2026-06-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_productmodel_tax_percent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
