# Generated by Django 6.0.6 on 2026-06-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_productmodel_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="goldpricemodel",
            name="is_active",
            field=models.BooleanField(default=True, unique=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="stock",
            field=models.PositiveIntegerField(default=0, verbose_name="Stock"),
        ),
    ]
