# Generated by Django 6.0.6 on 2026-06-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_goldpricemodel_is_active_alter_productmodel_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goldpricemodel",
            name="is_active",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
