# Generated by Django 6.0.6 on 2026-06-15 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_alter_goldpricemodel_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coinmodel",
            name="buy_price",
        ),
        migrations.RemoveField(
            model_name="coinmodel",
            name="sell_price",
        ),
    ]
