# Generated by Django 6.0.6 on 2026-06-16 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_remove_coinmodel_buy_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodel",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="product.categorymodel",
                verbose_name="Category",
            ),
        ),
    ]
