# Generated by Django 6.0.6 on 2026-06-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_alter_productmodel_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="coinmodel",
            name="status",
            field=models.CharField(
                choices=[("available", "Available"), ("out_of_stock", "Out Of Stock")],
                default="available",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
