# Generated by Django 6.0.6 on 2026-06-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_coinmodel_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorymodel",
            name="slug",
            field=models.SlugField(verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="slug",
            field=models.SlugField(verbose_name="Slug"),
        ),
    ]
