# Generated by Django 6.0.6 on 2026-06-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_alter_categorymodel_slug_alter_productmodel_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorymodel",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Slug"),
        ),
    ]
