# Generated by Django 6.0.6 on 2026-09-24 10:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0010_alter_categorymodel_slug_alter_productmodel_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="goldpricemodel",
            options={
                "verbose_name": "Price Board",
                "verbose_name_plural": "Price Boards",
            },
        ),
        migrations.AlterUniqueTogether(
            name="coinmodel",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="goldpricemodel",
            name="emami_coin",
        ),
        migrations.AddField(
            model_name="coinmodel",
            name="category",
            field=models.CharField(
                choices=[
                    ("bank", "Bank"),
                    ("parsian", "Parsian"),
                    ("market", "Market"),
                ],
                default=0,
                max_length=20,
                verbose_name="Category",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coinmodel",
            name="market_extra_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="Fixed fee added to market coin price (e.g., 600000)",
                max_digits=18,
                null=True,
                verbose_name="Extra Fee (Toman)",
            ),
        ),
        migrations.AddField(
            model_name="coinmodel",
            name="market_percent_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Percentage added to market coin price (e.g., 1 for 1%)",
                max_digits=5,
                null=True,
                verbose_name="Percent Fee (%)",
            ),
        ),
        migrations.AddField(
            model_name="goldpricemodel",
            name="effective_at",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="Effective At",
            ),
        ),
        migrations.AddField(
            model_name="goldpricemodel",
            name="gold_24",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=18,
                verbose_name="Gold 24K Price",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="goldpricemodel",
            name="internal_gold_17",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=18,
                verbose_name="Internal Gold 17K Price",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="goldpricemodel",
            name="silver_gram",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=18,
                verbose_name="Silver Gram Price (999)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="goldpricemodel",
            name="usd_price",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=18, verbose_name="USD Price"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productmodel",
            name="profit_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Seller profit percentage on base + wage",
                max_digits=5,
                verbose_name="Profit (%)",
            ),
        ),
        migrations.AlterField(
            model_name="categorymodel",
            name="title",
            field=models.CharField(max_length=255, unique=True, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="coinmodel",
            name="coin_type",
            field=models.CharField(
                blank=True,
                choices=[("quarter", "Quarter"), ("half", "Half"), ("full", "Full")],
                max_length=20,
                null=True,
                verbose_name="Coin Type",
            ),
        ),
        migrations.AlterField(
            model_name="coinmodel",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="product/coin/images",
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="coinmodel",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=10,
                null=True,
                verbose_name="Weight (grams)",
            ),
        ),
        migrations.AlterField(
            model_name="goldpricemodel",
            name="gold_melted",
            field=models.DecimalField(
                decimal_places=0, max_digits=18, verbose_name="Gold 18K Price"
            ),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="product/product/images",
                verbose_name="Image",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="coinmodel",
            unique_together={("category", "coin_type")},
        ),
    ]
