# Generated by Django 6.0.6 on 2026-06-04 15:50

import apps.account.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userbankaccount",
            options={
                "verbose_name": "Bank Account",
                "verbose_name_plural": "Bank Accounts",
            },
        ),
        migrations.RemoveField(
            model_name="userbankaccount",
            name="sheba_number",
        ),
        migrations.AddField(
            model_name="userbankaccount",
            name="iban",
            field=models.CharField(
                default=1,
                help_text="Iranian Sheba Number",
                max_length=26,
                validators=[apps.account.validators.validate_iban],
                verbose_name="IBAN",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userbankaccount",
            name="is_default",
            field=models.BooleanField(default=False, verbose_name="Default Account"),
        ),
        migrations.AlterField(
            model_name="userbankaccount",
            name="card_number",
            field=models.CharField(
                help_text="16-digit bank card number",
                max_length=16,
                validators=[apps.account.validators.validate_card_number],
                verbose_name="Card Number",
            ),
        ),
        migrations.AlterField(
            model_name="userbankaccount",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_accounts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
