# Generated by Django 6.0.6 on 2026-06-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_userbankaccount_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "کاربر", "verbose_name_plural": "کاربران"},
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="نام"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="فعال"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(default=False, verbose_name="ادمین"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="تأیید کنید"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="نام خانوادگی"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="national_code",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="کدملی"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                max_length=11, unique=True, verbose_name="شماره تماس"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("customer", "Customer")],
                default="customer",
                max_length=128,
                verbose_name="نقش",
            ),
        ),
        migrations.AlterField(
            model_name="userbankaccount",
            name="bank_name",
            field=models.CharField(blank=True, max_length=128, verbose_name="نام بانک"),
        ),
    ]
