# Generated by Django 6.0.6 on 2026-09-24 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

import apps.account.validators


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_user_options_alter_user_first_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userbankaccount",
            options={
                "verbose_name": "اطلاعات حساب بانکی",
                "verbose_name_plural": "Bank Accounts",
            },
        ),
        migrations.AlterField(
            model_name="userbankaccount",
            name="card_number",
            field=models.CharField(
                help_text="16-digit bank card number",
                max_length=16,
                validators=[apps.account.validators.validate_card_number],
                verbose_name="شماره کارت",
            ),
        ),
        migrations.AlterField(
            model_name="userbankaccount",
            name="iban",
            field=models.CharField(
                help_text="Iranian Sheba Number",
                max_length=26,
                validators=[apps.account.validators.validate_iban],
                verbose_name="شماره شبا",
            ),
        ),
        migrations.AlterField(
            model_name="userbankaccount",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_accounts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
    ]
