# Generated by Django 6.0.6 on 2026-06-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_alter_coininventorymodel_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallettransactionmodel",
            name="reference_id",
            field=models.CharField(
                db_index=True,
                default=1,
                max_length=50,
                unique=True,
                verbose_name="Reference ID",
            ),
            preserve_default=False,
        ),
    ]
