# Generated by Django 6.0.6 on 2026-06-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0003_wallettransactionmodel_reference_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallettransactionmodel",
            name="reference_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=50,
                unique=True,
                verbose_name="Reference ID",
            ),
        ),
        migrations.DeleteModel(
            name="CoinInventoryModel",
        ),
    ]
