# Generated by Django 6.0.6 on 2026-09-24 13:31

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0004_alter_wallettransactionmodel_reference_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoldPriceRuleModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update Time"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted Time"
                    ),
                ),
                (
                    "buy_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Buy Percent",
                    ),
                ),
                (
                    "sell_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Sell Percent",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Gold Price Rule",
                "verbose_name_plural": "Gold Price Rules",
            },
        ),
    ]
