# Generated by Django 6.0.6 on 2026-06-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmodel",
            name="expire_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Expire At"),
        ),
    ]
