# Generated by Django 6.0.6 on 2026-06-15 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_paymentmodel_expire_at"),
        ("product", "0005_alter_goldpricemodel_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmodel",
            name="locked_gold_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                default=0,
                max_digits=18,
                null=True,
                verbose_name="Locked Gold Price",
            ),
        ),
        migrations.AddField(
            model_name="paymentmodel",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="product.productmodel",
                verbose_name="Product",
            ),
        ),
        migrations.AddField(
            model_name="paymentmodel",
            name="tax_amount",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=18, verbose_name="Tax Amount"
            ),
        ),
        migrations.AddField(
            model_name="paymentmodel",
            name="wage_amount",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=18, verbose_name="Wage Amount"
            ),
        ),
        migrations.AddField(
            model_name="paymentmodel",
            name="weight",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=18, verbose_name="Weight"
            ),
        ),
    ]
