# Generated by Django 6.0.6 on 2026-06-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "payment",
            "0003_paymentmodel_locked_gold_price_paymentmodel_product_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmodel",
            name="locked_coin_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                default=0,
                max_digits=18,
                null=True,
                verbose_name="Locked Coin Price",
            ),
        ),
    ]
