# Generated by Django 6.0.6 on 2026-06-17 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0004_paymentmodel_locked_coin_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentmodel",
            name="locked_coin_price",
        ),
        migrations.RemoveField(
            model_name="paymentmodel",
            name="locked_gold_price",
        ),
        migrations.RemoveField(
            model_name="paymentmodel",
            name="product",
        ),
        migrations.RemoveField(
            model_name="paymentmodel",
            name="tax_amount",
        ),
        migrations.RemoveField(
            model_name="paymentmodel",
            name="wage_amount",
        ),
        migrations.RemoveField(
            model_name="paymentmodel",
            name="weight",
        ),
    ]
