# Generated by Django 6.0.6 on 2026-06-09 13:12

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update Time"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted Time"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("mobile-verification-code", "Mobile Verification Code"),
                            ("order-status", "Order Status"),
                            ("wallet-transaction", "Wallet Transaction"),
                            ("admin-alert", "Admin Alert"),
                        ],
                        max_length=50,
                        verbose_name="Notification Type",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Notif title")),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Notif description"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        max_length=512,
                        null=True,
                        upload_to="images/notifications/",
                    ),
                ),
                (
                    "kwargs",
                    models.JSONField(
                        blank=True, null=True, verbose_name="KeyWord args"
                    ),
                ),
                (
                    "send_notify",
                    models.BooleanField(default=True, verbose_name="Send Notify"),
                ),
                (
                    "is_showing",
                    models.BooleanField(default=True, verbose_name="Is showing"),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="To user",
                    ),
                ),
            ],
            options={
                "verbose_name": "اعلان",
                "verbose_name_plural": "Notifications",
                "ordering": ("-id",),
            },
        ),
    ]
