# Generated by Django 6.0.6 on 2026-06-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ("-id",),
                "verbose_name": "اعلان",
                "verbose_name_plural": "اعلان",
            },
        ),
        migrations.AlterField(
            model_name="notification",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="توضیحات متا"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="title",
            field=models.CharField(max_length=255, verbose_name="اعلان"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("mobile-verification-code", "Mobile Verification Code"),
                    ("order-status", "Order Status"),
                    ("wallet-transaction", "Wallet Transaction"),
                    ("admin-alert", "Admin Alert"),
                ],
                max_length=50,
                verbose_name="اعلان",
            ),
        ),
    ]
