# Generated by Django 6.0.6 on 2026-09-24 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0002_alter_notification_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="channel",
            field=models.CharField(
                choices=[("sms", "SMS"), ("in-app", "In App"), ("email", "Email")],
                default="in-app",
                max_length=50,
                verbose_name="Notification Channel",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_showing",
            field=models.BooleanField(default=True, verbose_name="مشاهده شده"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="kwargs",
            field=models.JSONField(
                blank=True, null=True, verbose_name="آرگومان\u200cهای کلمات کلیدی"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="send_notify",
            field=models.BooleanField(default=True, verbose_name="ارسال اعلانات"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="to_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="به کاربر",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("mobile-verification-code", "Mobile Verification Code"),
                    ("wallet-transaction", "Wallet Transaction"),
                    ("admin-alert", "Admin Alert"),
                    ("system", "System"),
                ],
                max_length=50,
                verbose_name="اعلان",
            ),
        ),
    ]
